---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postsvc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postsvc
  template:
    metadata:
      labels:
        app: postsvc
    spec:
      containers:
        - name: postsvc
          image: 172.16.0.18:5000/postsvc
          ports:
            - containerPort: 7075
          envFrom:
            - configMapRef:
                name: cm
---
apiVersion: v1
kind: Service
metadata:
  name: postsvc-rest
spec:
  selector:
    app: postsvc
  ports:
    - protocol: TCP
      port: 7075