---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxycm
data:
  config: |
    upstream websvc-rest {
        server websvc-rest.default.svc.cluster.local:7080 fail_timeout=0;
    }

    server {
        listen        80;
        server_name   localhost;

        location / {
            proxy_pass http://websvc-rest;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: confvol
      volumes:
        - name: confvol
          configMap:
            name: proxycm
            items:
              - key: config
                path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: proxysvc
spec:
  type: NodePort
  selector:
    app: proxy
  ports:
    - protocol: TCP
      port: 80