apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
data:
  MARIADB_SERVER_ADDR: dbsvc.default.svc.cluster.local
  MARIADB_SERVER_PORT: '3306'
  MARIADB_DB_USER: 'admin'
  MARIADB_DB_PASSWORD: 'abc123'
  MARIADB_DB_NAME: 'mariadb'
  LOGIN_SERVER_ADDR: loginsvc-rest.default.svc.cluster.local
  LOGIN_SERVER_PORT: '7070'
  MONGO_SERVER_ADDR: mongosvc.default.svc.cluster.local
  MONGO_SERVER_PORT: '27017'
  MONGO_DB_USER: admin
  MONGO_DB_PASSWORD: abc123
  FRONTEND_SERVER_ADDR: '10.110.35.110'
  FRONTEND_SERVER_PORT: '7080'
  POST_SERVER_ADDR: postsvc-rest.default.svc.cluster.local
  POST_SERVER_PORT: '7075'
